#!/usr/bin/env python3
"""Manual TCP test for ExaPlay."""

print("🧪 Manual ExaPlay TCP Test")
print("=" * 30)
print()
print("After configuring ExaPlay TCP, test manually:")
print()
print("1. Open Command Prompt or PowerShell")
print("2. Run: telnet localhost 7000")
print("3. Type: get:ver")
print("4. Press Enter")
print("5. You should see ExaPlay version response")
print()
print("If that works, then run:")
print("   python start_api.py")
print()
print("🔧 ExaPlay Configuration Reminder:")
print("   Settings → Comm → TCP Listen: *:7000")
print("   Make sure timeline 'test1' exists")
print("   Restart ExaPlay after configuration")
print()
print("📞 Common ExaPlay TCP Commands:")
print("   get:ver                  - Get version")
print("   hello                    - Test connection")
print("   get:status,test1         - Get timeline status") 
print("   play,test1               - Play timeline")
print("   stop,test1               - Stop timeline")
print()
print("✅ Once TCP works, your API will control timeline 'test1'!")
